### ISSUE TITLE
add `*.pdb` and `*.nc` to a .gitignore file?

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/sams#3]
Would it be worth adding a `.gitignore` file to avoid accidentally committing files that are too big to be stored on github?

**Comment by jchodera** [comment]
We use some PDB files as input, so that's not a good idea.

In general, this is what code review of PRs is for.

We should definitely prevent direct commits to master though

**Comment by steven-albanese** [comment]
ok! I'm going to close this issue if there are no objections
